### ISSUE TITLE
Use favourites from Safari bookmarks bar

### ISSUE THREAD

**Issue by robrecord** [umfana/FaviconBar#31] opened 2017-03-01 11:25 UTC
Rather than having its own selection of links, please allow the contents of the original Safari bookmarks bar to be displayed. This would save a lot of time, and would allow me to consider using the extension - as it is, I don't have time to set it up.

**Comment by popcornhax** [comment] 2017-03-26 20:17
This is on my long-term todo list, but I'm not 100% certain it's possible.  I know that I can't access Safari's favorites from within the extension so it would require writing an App Store app to do the conversion.  Due to the App Store's sandboxing I am not completely sure that favorites can be accessed from there either.  I'm not going to close it, but it's still up in the air.  Thanks for the suggestion.

**Comment by popcornhax** [comment] 2017-03-26 20:22
Actually since this is a duplicate of Issue #8 I am going to go ahead and close this request, but it's still planned.

**Closed as completed by popcornhax** 2017-03-26 20:22 UTC
