### ISSUE TITLE
Favicons Disappearing when Safari Restarted

### ISSUE THREAD

**Issue by melrose0517** [umfana/FaviconBar#24] opened 2017-02-08 15:07 UTC
Hi All, I am able to set up my favicons bar, no problem, and drag and drop and customize exactly as explained in readme page.  However, when I quit safari and reopen, the bar is completely blank again and I have to re-add all favicons.  I assume this is not the way this is supposed to work.  Is there some way to "save" my favicons bar so when I quit and restart, it is still there?

Thank you for the help!

**Comment by popcornhax** [comment] 2017-02-08 16:19
The favicons should save any time a change is made.  Which version of Safari are you using?  Can you think of any other unique settings you might have - such as running Safari in private mode or disabling cookies?  The bar saves items to Safari's built in Local Storage so it's possible those could have an effect

**Comment by melrose0517** [comment] 2017-02-08 16:22
I am running Safari Version 10.0.3 and OS Sierra 10.12.3.  I believe Safari has been installed with the default settings - nothing special that I know about.  I am actually making the transition from Chrome to Safari, hence my strong desire to have this favicons toolbar bc that is a feature i really liked about Chrome.  So no, I don't think I have anything special about my Safari install but I am happy to check things if you tell me what to check?!

**Comment by melrose0517** [comment] 2017-02-08 21:39
A new piece of information about this problem:  If I add a bunch of short-cuts in a row to the favicons bar, they don't all show up.  There is a placeholder where they SHOULD be and the link is active if you click in the blank space, but the physical icon is not pictured there.  It seems that there is some problem with the display of these. Is there a way to figure out where they are being stored in the local storage to see if they are there or not?  Thanks again for whatever help someone can give me!  I REALLY want this to work for me!

**Comment by popcornhax** [comment] 2017-02-08 21:46
Sometimes a box will show up if an icon doesn't load, such as when there is no internet connection.  First the toolbar will try to get an icon from an icon service, and if that fails it falls back to Google.  Usually Google won't fail.  

When you go to the settings page do they show up there?

The links are stored in the web browser's localStorage.  I don't know if there is any way to view that outside of when developing the extension.  

All this said, I really want to get this fixed for you.  I was in the same boat, I didn't think I could move from Chrome to Safari because of the lack of favicon bar.  Then I found this extension and while it was great I wanted to add a few more features.  

Are all settings lost after you close and reopen, including things like small/normal/large and round icons?  Or is it just the links?

Here's my current plan:
1) a bunch more testing tonight
2) going to make a version of the extension with logging that you could try so we can get more details, but that might take a few days.  That should be helpful in rooting out any future bugs.
3) in the meantime, you could use the older release (1.2), it stores the links in a different way but has fewer options.
4) if you don't want to use 1.2, you could export your links on the settings page and import them again every time it restarts, but that's really a workaround.

**Comment by melrose0517** [comment] 2017-02-08 22:13
Yes, when the icons are displayed, the links are listed when I open up the favicon bar settings.  If I close the window and re-open without fully quitting Safari, they are still there in both places as well (list of links and icons on bar).  However, when I Quit Safari and reopen, they are not there in either place (icons have disappeared from bar - it is just blank, and the links are no longer listed in the settings - there is nothing there at all).  However, the settings themselves are not lost (that I can tell).  I have "center the bar" and "blend into background" both checked and when I quit safari and reopen, those boxes are still checked but the links have all disappeared. 

Thank you for the help with this.  If we can not make this version work, I am open to trying the older version.  Could you point me in the direction of that link for download?

Thank you again!

**Comment by popcornhax** [comment] 2017-02-09 04:40
Well the "good" news is I was able to reproduce this on my older iMac.  I haven't been able to pin down why it's happening yet, but hopefully soon.

The older version is below, but I really hope to have this fixed within a couple days:
https://github.com/RoryCombe/FaviconBar/releases/tag/v1.2

**Comment by popcornhax** [comment] 2017-02-09 06:11
Hey, I think I have tracked down what was causing this bug and fixed it in this test build.  Can you possibly try it out?  It seems like this is something that would only happen on slightly slower/older macs...

https://github.com/dbrowder/FaviconBar/raw/master/FaviconBar.safariextz

Let me know if that works and we'll get it pushed to the main build.

**Comment by Blazej-pl** [comment] 2017-02-09 08:48
I can try it, but will my custom settings from current 1.3 be preserved? I've spend 2 hours crafting icons and I wouldn't like to start from scratch..

**Comment by melrose0517** [comment] 2017-02-09 13:06
I'd be happy to try anything but I must point out that I am working on a brand new (one week old) MacBook pro late 2016 edition (the brand new one with the touchbar), so I would think that this is not a slower/older mac problem and perhaps it is a compatibility issue with the brand new MacBook Pro?

Either way, I can download and install that one.  Does it override the one I have there now or do I need to uninstall that one first and then install the above one?

**Comment by melrose0517** [comment] 2017-02-09 13:18
IT WORKS!!!  I downloaded that test one, unchecked the original in the extension menu and only kept that one checked.  Then I added my favicons to the new bar and Quit Safari and reopened and they are all still there!!!  So whatever you did, works.  While I don't think the problems is older/slower macs (see my above post), the problem appears to be fixed none-the-less.  What is the next step?  Do i keep using this test one or should i uninstall both of these and install the main one again, once you have this change integrated!

Again, thank you, thank you, thank you!!!

**Comment by popcornhax** [comment] 2017-02-09 16:04
That's good to hear, thank you for testing. I guess the error being due to slow macs was a bad assumption. What really was happening is that there are two important files loaded when safari launches and one was runnin before the other was ready, so I just added an additional check. 

You can keep using this version for now, I have to clean up a few things and then I'll submit a request to Rory to add the fix into the main tree. 

Eventually you should probably move back to the main one, but you can always export your links and preferences from the settings page and bring them back in.

**Comment by melrose0517** [comment] 2017-02-10 17:53
Thank you so so so much for the help!!!  I SOOOO appreciate it!!!

**Comment by RoryCombe** [comment] 2017-02-13 12:09
Feel free to close this @dbrowder if it's solved

**Comment by popcornhax** [comment] 2017-02-14 16:57
Yep I think this one is resolved.

**Closed as completed by popcornhax** 2017-02-14 16:57 UTC
